MECH = {

    'Programming': ['COMPUTER PROGRAMMING'],

    'CS Fundamentals': ['OPERATING SYSTEMS', 'COMPUTER NETWORKS', 'COMPUTER ORGANIZATION'],

    'Mathematics and Logic': ['MATHEMATICS-1', 'MATHEMATICS-2', 'MATHEMATICS-3', 'PROBABILITY AND STATISTICS', 'DESIGN AND ANALYSIS OF ALGORITHMS', 'DISCRETE MATHEMATICS'],

    'Drawing': ['ENGINEERING DRAWING', 'ENGINEERING DRAWING FOR MECHANICAL ENGINEERING', 'MACHINE DRAWING', 'AUTOMOBILE ENGINEERING', 'CAD/CAM'],
    'Theoretical': ['MATERIAL SCIENCE AND ENGINEERING', 'MANUFACTURING TECHNOLOGY', 'ENTERPRENEURSHIP', 'MACHINE TOOLS', 'NON CINVENTIONAL SIOURCE OF ENERGY', 'METAL FORMING PROCESS', 'AUTOMOBILE ENGINEERING', 'CAD/CAM', 'METROLOGY AND MEASURMENTS', 'MODERN MANUFACTURING METHODS', 'AUTOMATION AND ROBOTICS'],
    'Problematic': ['AUTOMATION AND ROBOTICS', 'FINITE ELEMENT METHOD', 'HEAT TRANSFER', 'DESIGN OF MACHINE ELEMENTS-2', 'OPERATIONS RESEARCH', 'DESIGN OF MACHINE ELEMENTS-1', 'DYNAMICS OF MACHINERY', 'THERMAL ENGINEERING-2', 'FLUID MACHANIOCS AND HYDRAUILICS MACHINERY', 'THERMAL ENGINEERING-1', 'KINEMATICS OF MACHINES', 'THERMODYNAMICS', 'MECHANICS OF SOIDS']

}


EEE = {

    'Basic Programming Knowledge': ['DATA STRUCTURES', 'COMPUTER PROGRAMMING'],

    'Mathematics': ['MATHEMATICS-1', 'MATHEMATICS-2', 'MATHEMATICS-3', 'MATHEMATICS-4'],

    'Electrical Machines': ['ELECTRICAL MACHINES-1', 'ELECTRICAL MACHINES-2', 'ELECTRICAL-MACHINES-3'],

    'Electronics': ['ELECTRONIC DEVICES AND CIRCUITS', 'ANALOG ELECTRONIC CIRUITS', 'MICROPROCESSORS AND MICROCONTROLLERS'],

    'Circuits': ['ELECTRICAL CIRCUITS-1', 'ELECTRICAL CIRCUITS-2'],

    'Electrical Power Supply Systems': ['ELECTRICAL POWER GENERATING SYSTEMS', 'ELECTRICAL POWER TRANSMISSION SYSTEMS', 'ELECTRICAL DISTRIBUTION SYSTEMS'],

    'Power systems': ['POWER ELECTRONICS', 'POWER SEMI CONDUCTOR DRIVES', 'POWER SYSTEM OPERATION AND CONTROLS', 'POWER SYSTEM PROTECTION', 'POWER SYSTEM ANALYSIS'],

    'Networks and Digital Systems': ['DIGITAL SIGNAL PROCESSING', 'NEURAL NETWORKS AND FUZZY LOGIC', 'DIGITAL CIRCUITS AND SYSTEMS'],

    'Application and Engineering': ['CONTROL SYSTEM ENGINEERING', 'ELECTROMAGNETIC FIELD', 'ELECTRICAL MEASUREMENTS', 'LINEAR AND DIGITAL IC APPLICATIONS', 'UTILIZATION OF ELECTRICAL THEORY', 'ENERGY AUIDITING AND DEMAND MANAGEMENT', 'INSTRUMENTATION', 'ENERGY RESOURCES AND TECHNOLOGY']

}
CSE = {

    'Programming': ['COMPUTER PROGRAMMING', 'OBJECT ORIENTED PROGRAMMING USING JAVA'],

    'CS Fundamentals': ['OPERATING SYSTEMS', 'COMPUTER NETWORKS', 'COMPUTER ORGANIZATION'],

    'Mathematics and Logic': ['MATHEMATICS-1', 'MATHEMATICS-2', 'MATHEMATICS-3', 'PROBABILITY AND STATISTICS', 'DESIGN AND ANALYSIS OF ALGORITHMS', 'DISCRETE MATHEMATICS'],

    'Data Analytics': ['DATA WAREHOUSE AND MINING', 'DATA ANALYTICS', 'INTRODUCTION TO BIG DATA', 'DATABASE MANAGEMENT SYSTEMS'],

    'Cyber Security': ['INFORMATION SECURITY', 'CYBER SECURITY'],

    'Web Technologies': ['WEB & INTERNET TECHNOLOGIES', 'GRID & CLOUD COMPUTING'],

    'AI & ML': ['ARTIFICIAL INTELLIGENCE', 'MACHINE LEARNING'],

    'System Design': ['OBJECT ORIENTED ANALYSIS & DESIGN', 'FORMAL LANGUAGES AND AUTOMATA THEORY', 'DESIGN PATTERNS'],

    'Testing': ['SOFTWARE TESTING'],

    'Software Engineering': ['SOFTWARE ENGINEERING']

}

ECE = {


    'Basic CS': ['COMPUTER PROGRAMMING', 'DATA STRUCTURES', 'LINUX PROGRAMMING AND SCRIPTING', 'COMPUTER ORGANIZATION'],
    'Analog': ['NETWORK ANALYSIS', 'ELECTRONIC DEVICES AND CIRCUITS', 'ELECTRONIC CIRCUIT ANALYSIS', 'LINEAR INTEGRATED CIRCUITS AND APPLICATIONS', 'CONTROL SYSTEM ENGINEERING', 'ELECTRICAL TECHNOLOGY', 'EMBEDDED SYSTEM', 'ELECTRONIC MEASUREMENT AND INSTRUMENTATION'],
    'Digital': ['SWITCHING THEORY AND LOGIC DESIGN', 'DIGITAL SYSTEM DESIGN', 'MICROPROCESSORS AND MICRO CONTROLLERS', 'VLSI DESIGN'],
    'Communications': ['SIGNALS AND SYSTEMS', 'PROBABILITY THEORY AND STOCHASTIC PROCESSES', 'ANALOG COMMUNICATION SYSTEM', 'DIGITAL COMMUNICATION SYSTEM', 'ANTENNAS AND WAVE PROPAGATION', 'DIGITAL SIGNAL PROVCESSING', 'RADAR SYSTEMS', 'DATA COMMUNICATION AND NETWORKING', 'OPTICAL FIBER COMMUNICATION', 'ADVANCE DIGITAL SIGNAL PROCESSING', 'RADIO FREQUENCY INTEGRATED CURCUITS'],
    'Mathematics': ['MATHEMATICS-1', 'MATHEMATICS-2', 'MATHEMATICS-3', 'MATHEMATICS-4'],
    'Electrical': ['CONTROL SYSTEMS', 'ELECTRICAL TECHNOLOGY'],
    'Fundamental Science': ['ENGINEERING PHYSICS', 'ENGINEERING CHEMISTRY', 'ENVIRONMENTAL STUDIES']


}
