civil = {
    1: ['FUNCTIONAL ENGLISH', 'MATHEMATICS-1', 'COMPUTER PROGRAMMING', 'ENGINEERING PHYSICS', 'ENGINEERING DRAWING', 'ENGLISH LANGUAGE COMMUNICATION SKILLS LAB', 'ENGINEERING PHYSICS LAB', 'COMPUTER PROGRAMMING LAB'],
    2: ['ENGLISH FOR PROFESSIONAL COMMUNICATION', 'MATHEMATICS-2', 'ENGINEERING MECHANICS', 'ENGINEERING CHEMISTRY', 'ENVIRONMENTAL STUDIES', 'APPLIED MECHANICS LAB', 'ENGINEERING CHEMISTRYY LAB', 'ENGINEERING AND IT WORKSHOP'],
    3: ['MATHEMATICS-3', 'BUILDING MATERIAL AND CONSTRUCTION', 'STRENGTH OF MATERIAL-1', 'SURVEYING-1', 'FLUID MECHANICS', 'ELECTRICAL AND MECHANICAL TECHNOLOGY', 'SURVEYING LAB-1', 'STRENGTH OF MATERIALS LAB'],
    4: ['PROBABILITY AND STATISTICS', 'MANAGERIAL ECONOMICS AND FINANCIAL ANALYSIS', 'STRENGTH OF MATERIALS-2', 'SURVEYING-2', 'STRUCTURAL ANALYSIS-1', 'HYDRAULICS AND HYDRAULIC MACHINERY', 'FLUID MECHANICS AND HYDAULICS MACHINERY', 'SRVEYING LAB-2'],
    5: ['DESIGN AND DRAWING OF RCC STRUCTURES', 'ESTIMATION COSTING EVALUATION', 'GEOTECNICAL ENGINEERING-1', 'ENGINEERING GEOLOGY', 'STRUCTURAL ANALYSIS-2', 'WATER HARVESTING AND CONSERVATION', 'ENGINEERING GEOLOGY LAB-', 'GEOTECNICAL ENGINEERING LAB'],
    6: ['CONCRETE TECHNIOLOGY', 'DESIGN AND DRAWING OF STEEL STRUCTURES', 'GEOTECHNICAL ENGINBEERING-2', 'TRANSPORATAION ENGINEERIN G-1', 'WATER RESOURCES ENGINEERING-1', 'DISASTER MANAGEMENT AND MITIGATION', 'CONCRETE TECHNILOGY LAB', 'TRANSPORATAION TECHNOLOGY LAB'],
    7: ['FINIOTE ELEMENT METHOD', 'TRANSPORTAION ENGINEERING-2', 'ENVIRONMENTAL ENGINEERING', 'WATER RESOURCES ENGINEERING-2', 'GROUND IMPROVMENT TECHNIQUES', 'BRIDGE ENGINEERING', 'CAD LAB', 'ENVIRONMENTAL ENGINEERING LAB'],
    8: ['ADVANCED STRUCTURAL ENGINEERING ', 'ENVIRONMENTAL IMPACT ASSESSMENT AND MANAGEMENT ']
}
