cse = {1: ['FUNCTIONAL ENGLISH', 'MATHEMATICS', 'COMPUTER PROGRAMMING', 'ENGINEERING PHYSICS', 'ENGINEERING DRAWING', 'ENGINEERING PHYSICS LAB', 'ENGLISH LANGUAGE COMMUNICATION SKILLS LAB', 'COMPUTER PROGRAMMING LAB'],
 2: ['ENGLISH FOR PROFESSIONAL COMMUNICATION', 'MATHEMATICS', 'DATA STRUCTURES', 'ENGINEERING CHEMISTRY', 'ENVIRONMENTAL STUDIES', 'DATA STRUCTURES LAB', 'ENGINEERING CHEMISTRY LAB', 'ENGINEERING & IT WORKSHOP'],
 3: ['MATHEMATICS', 'DATABASE MANAGEMENT SYSTEMS', 'DISCRETE MATHEMATICS', 'BASIC ELECTRICAL AND ELECTRONICS ENGINEERING', 'DIGITAL LOGIC DESIGN', 'MANAGERIAL ECONOMICS AND FINANCIAL ANALYSIS', 'DATABASE MANAGEMENT SYSTEMS LAB', 'BASIC ELECTRICAL AND ELECTRONICS ENGINEERING LAB'],

 4: ['PROBABILITY AND STATISTICS ', 'SOFTWARE ENGINEERING', 'COMPUTER ORGANIZATION', 'MICROPROCESSING AND INTERFACING', 'OBJECT ORIENTED PROGRAMMING USING JAVA', 'FORMAL LANGUAGES AND AUTOMATA THEORY', 'MICROPROCESSING AND INTERFACING LAB', 'JAVA PROGRAMMING LAB'],

 5: ['OPERATING SYSTEMS ', 'COMPUTER NETWORKS', 'OBJECT ORIENTED ANALYSIS & DESIGN', 'PRINCIPLES OF PROGRAMMING LANGUAGES', 'SOFTWARE TESTING', 'INTRODUCTION TO BIG DATA', 'OBJECT ORIENTED ANALYSIS & DESIGN AND SOFTWARE TESTING LAB', 'OPERATING SYSTEMS LAB'],
 6: ['COMPILER DESIGN', 'DATA WAREHOUSING & MINING', 'DESIGN PATTERNS', 'DESIGN & ANALYSIS OF ALGORITHMS', 'WEB & INTERNET TECHNOLOGIES', 'ARTIFICIAL INTELLIGENCE', 'WEB & INTERNET TECHNOLOGIES LAB', 'DATA WAREHOUSING & MINING LAB'],

 7: ['GRID & CLOUD COMPUTING', 'INFORMATION SECURITY', 'MOBILE APPLICATION DEVELOPMENT', 'MACHINE LEARNING', 'SOFTWARE PROJECT MANAGEMENT', 'GRID & CLOUD COMPUTING LAB', 'MOBILE APPLICATION DEVELOPMENT LAB', 'MANAGEMENT SCIENCE '],
 8: ['CYBER SECURITY ', 'DATA ANALYTICS ']}
