eee = {
    1: ['FUNCTIONAL ENGLISH', 'MATHEMATICS-1', 'COMPUTER PROGRAMMING', 'ENGINEERING PHYSICS', 'ENGINEERING DRAWING', 'ENGLISH LANGUAGE COMMUNICATION SKILLS LAB', 'ENGINEERING PHYSICS LAB', 'COMPUTER PROGRAMMING LAB'], 
    2: ['ENGLISH FOR PROFESSIONAL COMMUNICATION', 'MATHEMATICS -2', 'ELECTRICAL CIRCUITS-1', 'ENGINEERING CHEMISTRY', 'ENVIRONMENTAL STUDIES', 'ELECTRICAL CIRCUITS LAB', 'ENGINEERING CHEMISTRYY LAB', 'ENGINEERING AND IT WORKSHOP'], 
    3: ['MATHEMATICS-3', 'ELECTRICAL CIRCUITS-2', 'DATA STRUCTURES', 'ELECTRICAL MACHINES-2', 'CONTROL SYSTEM ENGINEERING', 'ELECTRONIC DEVICES AND CIRCUITS', 'ELECTRONIC DEVICES AND CIRCUITS LAB'], 
    4: ['MATHEMATICS-4', 'ELECTRICAL MACHINES-2', 'ELECTRICAL POWER GENERATION SYSTEM', 'ELECTROMAGNETIC FIELD', 'ANALOG ELECY=TRONIC CIRCUITS', 'MANAGERIAL ECONPMICS AND FINANCIAL ANALYSIS', 'ELECTRICAL MACHINES LAB-1', 'CONTROL SYSTEM AND SIMULATIN LAB'], 
    5: ['ELECTRICAL MEASUREMENTS', 'ELECTRICAL POWER TRANSMISSION SYSTEM', 'POWER ELECTRONICS', 'ELECTRICAL MACHINES-2', 'LINEAR AND DIGITAL IC APPLICATIONS', 'DIGITAL CIRCUITS AND SYSTEMS', 'ELECTRICAL MACHINES ALB-2', 'ELECTRICAL MEASURMENT LAB'], 
    6: ['POWER SEMI CONDUCTOR DRIVES', 'POWER SYSTEM PROTECTION', 'POWER SYSTEM ANALYSIS', 'NEURAL NETWORKS AND FUZZY LOGIC', 'MIOCROPROCESSOR AND MICROCONTROLLERS', 'MANAGMRNT SCIENCE', 'POWER ELECTRONICS SIMLATION LAB', 'MICROPROCESSOR AND MICROCONTROLLERS LAB'], 
    7: ['ELECTRICAL DISTRIBUTION SYSTEM', 'POWER SYSTEM PERATION AND CINTROLS', 'UTILZATION OF ELECTRICAL THEORY', 'ENERGY AUIDITING AND DEMAND MANAGEMENT', 'POWER QUALITY', 'DIGITAL SIGNAL PROCESSING', 'DIGITAL SIGNAL PROCESSING LAB', 'POWER SYSTEM AND SIMULATION LAB'], 
    8: ['INSTRUMENTATION', 'ENERGY RESOURCES AND TECHNOLOGY ']
    }