mech = {
    1: ['FUNCTIONAL ENGLISH', 'MATHEMATICS-1', 'COMPUTER PROGRAMMING', 'ENGINEERING CHEMISTRY', 'ENVIRONMENTAL STUDIES', 'ENGLISH LANGUAGE COMMUNICATION SKILLS LAB', 'ENGINEERING CHEMISTRY LAB', 'COMPUTER PROGRAMMING LAB'],
    2: ['ENGLISH FOR PROFESSIONAL COMMUNICATION', 'MATHEMATICS-2', 'MATERIAL SCIENCE AND ENGINEERING', 'ENGINEERING PHYSICS', 'ENGINEERING DRAWING', 'MATERIAL SCIENCE AND ENGINEERING LAB', 'ENGINEERING PHYSICS LAB', 'ENGINEERING AND IT WORKSHOP'],
    3: ['MATHEMATICS-3', 'MANEGERIAL ECONOMICS AND FINANCIAL ANALYSIS', 'MECHANICS OF SOIDS', 'ENGINEERING DRAWING FOR MECHANICAL ENGINEERING', 'ENGINEERING MECHANICS', 'THERMODYNAMICS', 'COMPUTER AIDED DRAFTING LAB', 'MECGHANICS OF SOLIDS LAB'],
    4: ['PROBABILITY AND STATISTICS', 'BASIC ELECTRICAL AND ELECTRONICS ENGINEERING', 'KINEMATICS OF MACHINES', 'THERMAL ENGINEERING-1', 'MANUFACTURING TECHNOLOGY', 'MACHINE DRAWING', 'THERMAL ENGINEERING LAB', 'MANUFACTURING TECHNOLOGY LAB'],
    5: ['FLUID MACHANIOCS AND HYDRAUILICS MACHINERY', 'THERMAL ENGINEERING -2', 'DYNAMICS OF MACHINERY', 'DESIGN OF MACHINE ELEMENTS-1', 'ENTERPRENEURSHIP', 'MACHINE TOOLS', 'FLUID MACHANIOCS AND HYDRAUILICS MACHINERY LAB', 'MACHINE TOOLS LAB'],
    6: ['OPERATIONS RESEARCH', 'DESIGN OF MACHINE ELEMENTS-2', 'HEAT TRANSFER', 'FINITE ELEMENT METHOD', 'NON CINVENTIONAL SIOURCE OF ENERGY', 'METAL FORMING PROCESS', 'HEAT TRANSFER LAB', 'COMPUTER AIDED ENGINEERING LAB'],
    7: ['AUTOMOBILE ENGINEERING', 'CAD/CAM', 'METROLOGY AND MEASURMENTS', 'MODERN MANUFACTURING METHODS', 'AUTOMATION AND ROBOTICS', 'MANAGEMENT SCIENCE', 'CAD/CAM LAB', 'METROLOGY AND MEASURMENTS LAB'],
    8: ['POWER PLANT ENGINEERING ', 'INDUSTRIAL ENGINEERING ']
}
