# Generated by Django 3.1.5 on 2021-06-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('sem_no', models.IntegerField(default=1)),
                ('roll_no', models.CharField(max_length=10)),
                ('s1', models.IntegerField(default=0)),
                ('s2', models.IntegerField(default=0)),
                ('s3', models.IntegerField(default=0)),
                ('s4', models.IntegerField(default=0)),
                ('s5', models.IntegerField(default=0)),
                ('s6', models.IntegerField(default=0)),
                ('s7', models.IntegerField(default=0)),
                ('s8', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.IntegerField(default=1)),
                ('roll_no', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('cst', models.IntegerField(default=0)),
                ('ot', models.IntegerField(default=0)),
                ('csp', models.IntegerField(default=0)),
                ('op', models.IntegerField(default=0)),
                ('s1', models.CharField(blank=True, max_length=100)),
                ('s2', models.CharField(blank=True, max_length=100)),
                ('s3', models.CharField(blank=True, max_length=100)),
                ('s4', models.CharField(blank=True, max_length=100)),
                ('s5', models.CharField(blank=True, max_length=100)),
                ('s6', models.CharField(blank=True, max_length=100)),
                ('s7', models.CharField(blank=True, max_length=100)),
                ('s8', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
